# Generated by Django 4.1.13 on 2024-03-09 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="number",
            field=models.CharField(
                default=uuid.UUID("48460d63-c407-4832-a6dc-f93b1f338d0e"),
                max_length=36,
                unique=True,
            ),
        ),
    ]
